name: Build & Deploy All

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - run: npm ci
    - run: |
        rm -rf dist
        npx babel scripts --out-dir dist --copy-files --presets @babel/preset-env,@babel/preset-react
        cp index.html dist/
        cp -r styles/ dist/styles/
        cp -r assets/ dist/ 2>/dev/null || true
        cp -r images/ dist/ 2>/dev/null || true
        
        echo "📁 Build abgeschlossen - Dist Inhalt:"
        ls -la dist/
        ls -la dist/styles/ || echo "styles nicht gefunden"
    - uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artefacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: .
        
    - name: Überprüfe Dateien
      run: |
        echo "📁 Aktuelles Verzeichnis:"
        ls -la
        echo ""
        echo "📁 Dist Ordner Inhalt:"
        ls -la dist/ || echo "dist/ existiert nicht"
        echo ""
        echo "📁 Styles Ordner:"
        ls -la dist/styles/ || echo "styles/ existiert nicht"
        
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
