name: Build & Deploy All

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Babel Build
        run: npx babel scripts --out-dir dist --copy-files --presets @babel/preset-env,@babel/preset-react

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Deploy via GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}   # <-- Dein Personal Access Token als Secret anlegen
          publish_branch: gh-pages              # Branch, auf den deployed wird
          publish_dir: ./dist                   # Direkt der dist-Ordner
          force_orphan: true                    # Frischer Commit im gh-pages Branch
