- name: Build with Babel
      run: |
        rm -rf dist
        npx babel scripts --out-dir dist --copy-files --presets @babel/preset-env,@babel/preset-react
        
        # ERSTELLE index.html falls nicht vorhanden
        if [ ! -f "index.html" ]; then
          echo "⚠️  index.html nicht gefunden - erstelle eine..."
          cat > dist/index.html << 'EOL'
<!DOCTYPE html>
<html>
<head>
    <title>App</title>
</head>
<body>
    <div id="root"></div>
    <script src="scripts/App.js"></script>
</body>
</html>
EOL
        else
          echo "✅ Kopiere index.html"
          cp index.html dist/
        fi
        
        cp -r styles/ dist/styles/ 2>/dev/null || true
